# network architecture
# encoder related
etype: vggblstmp     # encoder architecture type
elayers: 6
eunits: 512
eprojs: 512
dropout-rate: 0.2
subsample: "1_2_2_1_1" # skip every n frame from input to nth layers
# decoder related
dtype: lstm
dlayers: 2
dunits: 512
dropout-rate-decoder: 0.1
# attention related
atype: location
adim: 512
aconv-chans: 10
aconv-filts: 100

# hybrid CTC/attention
mtlalpha: 0.5

# minibatch related
batch-size: 30
maxlen-in: 800  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen_out, batchsize is automatically reduced

# optimization related
opt: adadelta
epochs: 20
patience: 3

# scheduled sampling option
sampling-probability: 0.2
n-iter-processes: 16
report-cer: True
save-interval-iters: 100
num-save-attention: 10
